name: X-Socials
version: 1.5
api-version: 1.13
main: com.fabian.xsocials.XSocials
folia-supported: true
authors: [Fabian]
website: https://xproyects.qzz.io
description: "Simple social media plugin. You can add as many networks as you want, and they are customizable."
softdepend: [PlaceholderAPI]

commands:
  xsocials:
    description: Main command for X-Socials
    aliases: [xs]
    usage: /<command> [reload|update|list|edit|<social>]
    permission: xsocials.use

permissions:
  xsocials.*:
    description: Full access to all X-Socials features
    children:
      xsocials.admin: true
  xsocials.admin:
    description: Allows using the editor and managing socials
    default: op
    children:
      xsocials.reload: true
      xsocials.update: true
      xsocials.gui: true
      xsocials.admin.forcemessages: true
  xsocials.use:
    description: Allows using the basic social commands
    default: true
  xsocials.gui:
    description: Allows managing and editing social networks via GUI
    default: op
  xsocials.reload:
    description: Allows reloading the plugin configuration
    default: op
  xsocials.update:
    description: Allows checking for plugin updates
    default: op
  xsocials.admin.forcemessages:
    description: Allows force-updating or regenerating message files
    default: op